[[redirects]]
    from = "/*"
    to = "/"
    status = 200

[[redirects]]
    from = "http://calc.nin.red/*"
    to = "https://calcium.js.org"
    status = 302

[[redirects]]
    from = "https://calc.nin.red/*"
    to = "https://calcium.js.org"
    status = 302
