name: Build Apk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install

    - name: Build the original project
      run: npm run build
    
    - name: Build Apk
      uses: darkshredder/web-to-app-action@main
      with:
          build-folder-path: 'build'
          app-name: 'Calcium'
          output-folder-path: 'apk/'
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Final-apks
        path: apk/
